index.md

I added a description of how the deployment considerations can be used in the creation of POUFs.

Added POUF description to the home page

---

ecus.md

Added images and did some capitalization changes.

ECU page updates

---

repositories.md

I added the four missing figures, filled in some missing links, checked capitalization, and changed a few musts.
We have some empty headers here at the bottom that I think can be eliminated as I can't find appropriarte copy for them.

Additional work on Repositories

---

exceptional_operations.md

Can we get some eyes on the section about aftermarket ECUs? When I was reviewing this for tone, I found the last sentence in that paragraph was incomplete or just missing a few critical word or two. I attempted to fix it, but I don't know if more needed to be done.
Lois

Minor changes to exceptional ops

---

normal_operation.md

A quick pass through for readability

sentence-level edits

---

repositories.md

also fixing some capitalization choices

Wordsmithing repositories

---

exceptional_operations.md

Fixes https://github.com/uptane/uptane-standard/issues/149.

Delegations can be removed from the Snapshot after rotation.

---

customizations.md

Fixes https://github.com/uptane/uptane-standard/issues/161.

Add section for location based updates.

---

key_management.md

Proposal for fixing #47. Also added normative reference for IETF RFC 4107 / BCP 107.

Updated key_management.md to fix #47

---

repositories.md

Changed one sentence to close out Issue #51

modification to close Issue #51

---

security_considerations.md

I added a few lines of text to the Enhanced Security section to address Issue #46. Please feel free to add or modify.

Added text to close Issue #46

---

changelog.md

This is a quick list of all the changes made to the Standard since July 31, 2019.  Per @iramcdonald, I made this a bulleted list. I also combined items where it seemed relevant.

Added text for Changelog

---

README.md
_data/navbar.yml
index.md

I have not changed the name of the repo itself nor the website URLs. It is debatable if either is actually worth changing.

Rename to "Deployment Best Practices".

---

repositories.md

Standardize "implementer".

---

faq.md

This adds a cross-reference link between the FAQ and the Customizations section about using Uptane with other systems

A little cleanup work--added a link

---

repositories.md

The Director only needs images if it will be encrypting them.

---

changelog.md

Added all the significant changes made to the Standard during our proofreading sessions

Updated Changelog to reflect recent changes

---

changelog.md

I used the link @plapczyn provided in Issue #89 to edit and reformat the Changelog. This now should fit the stipulations in that document. The one thing I was unsure about was how in-depth  the "Unreleased" section should be. The document said it should list issues/changes not yet released. We current have over 20 such issues, including some we know may not be addressed promptly. Perhaps @plapczyn and.or @iramcdonald can provide input and advice. @tkfu this revised changelog would need to be included in your proposed Deployment Best Practices document.

Changing the changelog

---

glossary.md
regulations_and_standards.md

As requested by @jhdalek55 in https://github.com/uptane/deployment-considerations/issues/83.

Add blank pages for glossary and regulations.

---

security_considerations.md

Adds a description of https://github.com/uptane/uptane-standard/issues/202 and how to mitigate it.

Add mitigation for uptane-standard issue #202

---

regulations_and_standards.md

This is an extremely rough draft. I had a surprisingly difficult time coming up with short descriptions of these regulations. The official pages for the two ISO standards literally list only what iteration they were on and title.  I could find nothing in the way of a general explanation of ISO21434. I also know that there are probably a few more regulations that should be on this initial post. I just wanted to get something on the page so we can begin to get this built. So, please, add, subtract, change or point me in the right direction for better sources. Thanks.

Add text to regulations and standards

---

glossary.md

At the suggestion of  @iramcdonald this PR adds accepted definitions of trust and its various other word forms to the Glossary.

Adding definitions of trust-Resolves Issue #85

---

emerging_issues.md

Add file for emerging issues

---

glossary.md

Modify ECU identifier  definition as "a globally unique attribute....'  Closes Issue #106

Change definition to close Issue #106

---

changelog.md

This brief addition includes ONLY changes made to the Standard.
Can we get an approval so we can merge this to the final version.

Update changelog for V.1.2.0

---

changelog.md

First set of proofreading corrections from pre-release review.

Proofreading corrections for V.1.2.0

---

glossary.md

Given the importance of understanding the meaning of conformance terms, it should be in both documents.

Added conformance terminology

---

repositories.md

I merged the open Pull Request for the issue (#124 ) because additional edits were needed and I could not make them within the review. Can one or two people (@tkfu or @trishankatdatadog  or @pattivacek ) please review this new Pull Request and let me know if I cut too little or too much?

More changes to remove time server references

---

customizations.md

Please kindly check this minor fix for the typo in the customizations.md, thanks!

docs: fix typo UI->URI in customizations.md

---

key_management.md

Adding suggested changes of @tkfu from Issue #136

Addressing Issue #136

---

glossary.md

Add link to RFC 2119
